name: 🐧 Build for Linux x86_64 and Android

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

env:
  unity_version: "2022.3.7f1"
  release_body: "uwu"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build game for Linux
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          versioning: Tag
          unityVersion: ${{ env.unity_version }}
          targetPlatform: StandaloneLinux64
      - name: Prepare game files for release
        run: |
          sudo rm -rf build/StandaloneLinux64/StandaloneLinux64_BackUpThisFolder_ButDontShipItWithYourGame
          sudo mv build/StandaloneLinux64/StandaloneLinux64_Data build/StandaloneLinux64/MothershipDefender2_Data
          sudo mv build/StandaloneLinux64/StandaloneLinux64 build/StandaloneLinux64/MothershipDefender2.x86_64
          sudo chmod a+x build/StandaloneLinux64/MothershipDefender2.x86_64
          sudo mv build/StandaloneLinux64 build/MothershipDefender2
          sudo tar -cJf build/MothershipDefender2.tar.xz -C build MothershipDefender2
      - name: Upload game to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: build/MothershipDefender2.tar.xz
          tag: ${{ github.ref }}
          body: ${{ env.release_body }}

      - run: docker system prune -af
      - name: Build game for Android
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          versioning: Tag
          unityVersion: ${{ env.unity_version }}
          targetPlatform: Android
          androidKeystoreName: user.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
      - name: Prepare files for release
        run: |
          sudo mv build/Android/Android.apk build/Android/MothershipDefender2.apk
          sudo mv build/Android/Android.main.obb build/Android/MothershipDefender2.main.obb
      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: build/Android/MothershipDefender2.*
          tag: ${{ github.ref }}
          file_glob: true
          body: ${{ env.release_body }}
