name: 🪟 Build for Windows x86_64

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

env:
  unity_version: "2022.3.7f1"
  release_body: "uwu"

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build game for Windows
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          versioning: Tag
          unityVersion: ${{ env.unity_version }}
          targetPlatform: StandaloneWindows64
      - name: Prepare files for release
        run: |
          Remove-Item build/StandaloneWindows64/StandaloneWindows64_BackUpThisFolder_ButDontShipItWithYourGame -Recurse -Force
          Move-Item build/StandaloneWindows64/StandaloneWindows64_Data build/StandaloneWindows64/MothershipDefender2_Data
          Move-Item build/StandaloneWindows64/StandaloneWindows64.exe build/StandaloneWindows64/MothershipDefender2.exe
          Move-Item build/StandaloneWindows64 build/MothershipDefender2
          Compress-Archive -Path build/MothershipDefender2 -DestinationPath build/MothershipDefender2.zip
      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: build/MothershipDefender2.zip
          tag: ${{ github.ref }}
          body: ${{ env.release_body }}
